drivers: input: making sure correct values get exported
For some reasons some expected values (CONFIG_OPPO_FINGERPRINT_PROJCT=19631 & CONFIG_OPPO_FINGERPRINT_PLATFORM=6125) was not getting exported correctly and causing the error

CC      drivers/input/misc/oppo_seccommon_drivers/oppo_secure_common/oppo_secure_common.o
../drivers/input/misc/oppo_seccommon_drivers/oppo_secure_common/oppo_secure_common.c:34:10: fatal error: 'soc/qcom/smem.h' file not found
#include <soc/qcom/smem.h>
         ^~~~~~~~~~~~~~~~~
  CC      net/ipv6/ip6_fib.o
1 error generated.
make[5]: * [../scripts/Makefile.build:362: drivers/input/misc/oppo_seccommon_drivers/oppo_secure_common/oppo_secure_common.o] Error 1
make[4]: * [../scripts/Makefile.build:676: drivers/input/misc/oppo_seccommon_drivers/oppo_secure_common] Error 2
make[3]: * [../scripts/Makefile.build:676: drivers/input/misc/oppo_seccommon_drivers] Error 2
make[2]: * [../scripts/Makefile.build:676: drivers/input] Error 2
make[2]: *** Waiting for unfinished jobs....

So the fix was basically to remove other conditions to get the value we need